// <auto-generated />
using System;
using DeliveryFilter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryFilter.Migrations
{
    [DbContext(typeof(DeliveryContext))]
    partial class DeliveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("DeliveryFilter.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("6367348f-c993-479f-88ad-a23f276ba390"),
                            DeliveryTime = new DateTime(2024, 10, 29, 18, 39, 49, 882, DateTimeKind.Local).AddTicks(5193),
                            District = "Центральный",
                            Weight = 1.5
                        },
                        new
                        {
                            OrderId = new Guid("3d6d6501-c782-4638-99ef-8f428c6c85b8"),
                            DeliveryTime = new DateTime(2024, 10, 29, 19, 39, 49, 882, DateTimeKind.Local).AddTicks(5205),
                            District = "Северный",
                            Weight = 2.0
                        },
                        new
                        {
                            OrderId = new Guid("d89bd7d0-b4c6-4797-a47d-59a46bcea392"),
                            DeliveryTime = new DateTime(2024, 10, 29, 20, 39, 49, 882, DateTimeKind.Local).AddTicks(5207),
                            District = "Южный",
                            Weight = 1.0
                        },
                        new
                        {
                            OrderId = new Guid("c66e328b-847a-459d-8892-0e24b12507f1"),
                            DeliveryTime = new DateTime(2024, 10, 29, 21, 39, 49, 882, DateTimeKind.Local).AddTicks(5208),
                            District = "Западный",
                            Weight = 2.5
                        },
                        new
                        {
                            OrderId = new Guid("6aa00f6c-b1e4-4952-89c1-e23ecb996244"),
                            DeliveryTime = new DateTime(2024, 10, 29, 22, 39, 49, 882, DateTimeKind.Local).AddTicks(5209),
                            District = "Восточный",
                            Weight = 3.0
                        },
                        new
                        {
                            OrderId = new Guid("63873da0-dffb-41a7-bc80-5359a165fffa"),
                            DeliveryTime = new DateTime(2024, 10, 29, 18, 54, 49, 882, DateTimeKind.Local).AddTicks(5211),
                            District = "Ленинский",
                            Weight = 1.2
                        },
                        new
                        {
                            OrderId = new Guid("629a5460-5628-43af-9838-62c520de58f6"),
                            DeliveryTime = new DateTime(2024, 10, 29, 20, 9, 49, 882, DateTimeKind.Local).AddTicks(5212),
                            District = "Советский",
                            Weight = 2.2999999999999998
                        },
                        new
                        {
                            OrderId = new Guid("86430cc9-7346-4eb6-a295-10a7d6515600"),
                            DeliveryTime = new DateTime(2024, 10, 29, 21, 24, 49, 882, DateTimeKind.Local).AddTicks(5214),
                            District = "Кировский",
                            Weight = 1.8
                        },
                        new
                        {
                            OrderId = new Guid("6af9470c-69ef-4788-a0ee-0ee9e9f988b0"),
                            DeliveryTime = new DateTime(2024, 10, 29, 21, 59, 49, 882, DateTimeKind.Local).AddTicks(5218),
                            District = "Московский",
                            Weight = 2.1000000000000001
                        },
                        new
                        {
                            OrderId = new Guid("5cb76fea-875e-4289-8b99-2d796fad4e6b"),
                            DeliveryTime = new DateTime(2024, 10, 29, 22, 49, 49, 882, DateTimeKind.Local).AddTicks(5220),
                            District = "Промышленный",
                            Weight = 3.5
                        },
                        new
                        {
                            OrderId = new Guid("6d7667d4-e42a-45f9-89c0-58b636ec1fa8"),
                            DeliveryTime = new DateTime(2024, 10, 29, 23, 39, 49, 882, DateTimeKind.Local).AddTicks(5221),
                            District = "Спортивный",
                            Weight = 1.8999999999999999
                        },
                        new
                        {
                            OrderId = new Guid("2e233196-a8ff-49d3-b486-6b44a638e10d"),
                            DeliveryTime = new DateTime(2024, 10, 29, 19, 9, 49, 882, DateTimeKind.Local).AddTicks(5223),
                            District = "Научный",
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            OrderId = new Guid("66754d73-b445-49a4-aa6e-8765d2dc90f5"),
                            DeliveryTime = new DateTime(2024, 10, 29, 19, 54, 49, 882, DateTimeKind.Local).AddTicks(5224),
                            District = "Культурный",
                            Weight = 1.3999999999999999
                        },
                        new
                        {
                            OrderId = new Guid("62a4e96b-e759-48f8-bd14-3e4485d2afd3"),
                            DeliveryTime = new DateTime(2024, 10, 29, 20, 44, 49, 882, DateTimeKind.Local).AddTicks(5226),
                            District = "Промышленный",
                            Weight = 3.1000000000000001
                        },
                        new
                        {
                            OrderId = new Guid("abee5e5b-dabb-4e70-88af-46fc7c7da9f6"),
                            DeliveryTime = new DateTime(2024, 10, 29, 22, 29, 49, 882, DateTimeKind.Local).AddTicks(5227),
                            District = "Гармоничный",
                            Weight = 2.6000000000000001
                        },
                        new
                        {
                            OrderId = new Guid("c4a3cf83-a0c8-4b34-be34-0afcf5e427f3"),
                            DeliveryTime = new DateTime(2024, 10, 29, 23, 4, 49, 882, DateTimeKind.Local).AddTicks(5228),
                            District = "Парк",
                            Weight = 1.3
                        },
                        new
                        {
                            OrderId = new Guid("f82b3597-f92f-4c40-b26d-116e60f99762"),
                            DeliveryTime = new DateTime(2024, 10, 30, 0, 9, 49, 882, DateTimeKind.Local).AddTicks(5232),
                            District = "Уютный",
                            Weight = 2.3999999999999999
                        },
                        new
                        {
                            OrderId = new Guid("1cb0139e-60e5-4cb7-adf7-8e56803a03cd"),
                            DeliveryTime = new DateTime(2024, 10, 29, 19, 19, 49, 882, DateTimeKind.Local).AddTicks(5233),
                            District = "Торговый",
                            Weight = 1.6000000000000001
                        },
                        new
                        {
                            OrderId = new Guid("c8abffed-ada1-4919-b23c-22230d96b0db"),
                            DeliveryTime = new DateTime(2024, 10, 29, 19, 49, 49, 882, DateTimeKind.Local).AddTicks(5235),
                            District = "Исторический",
                            Weight = 3.2000000000000002
                        },
                        new
                        {
                            OrderId = new Guid("dcaa8ca1-6689-4517-be4b-3be9d29401ee"),
                            DeliveryTime = new DateTime(2024, 10, 29, 21, 14, 49, 882, DateTimeKind.Local).AddTicks(5236),
                            District = "Экологический",
                            Weight = 2.7000000000000002
                        },
                        new
                        {
                            OrderId = new Guid("634c7ce1-33cb-49ee-838a-80bb4e67af19"),
                            DeliveryTime = new DateTime(2024, 10, 29, 21, 44, 49, 882, DateTimeKind.Local).AddTicks(5238),
                            District = "Промышленный",
                            Weight = 2.8999999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
